import { CAR_VALIDATION_LIMITS } from "../../limit/car/car.limit";
import VALIDATION_MESSAGES from "../message.message";

export const CAR_VALIDATION_MESSAGES = {
  BRAND_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Brand"),
  MODEL_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Model"),
  YEAR_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Year"),
  COLOR_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Color"),
  PRICE_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Price per day"),
  SEATS_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Number of seats"),
  AC_REQUIRED: VALIDATION_MESSAGES.REQUIRED("AC status"),
  ID_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Car ID"),
  INVALID_ID: VALIDATION_MESSAGES.INVALID_FORMAT("Car ID"),

  BRAND_MIN: VALIDATION_MESSAGES.MIN_LENGTH(
    "Brand",
    CAR_VALIDATION_LIMITS.BRAND.MIN
  ),
  BRAND_MAX: VALIDATION_MESSAGES.MAX_LENGTH(
    "Brand",
    CAR_VALIDATION_LIMITS.BRAND.MAX
  ),
  MODEL_MIN: VALIDATION_MESSAGES.MIN_LENGTH(
    "Model",
    CAR_VALIDATION_LIMITS.MODEL.MIN
  ),
  MODEL_MAX: VALIDATION_MESSAGES.MAX_LENGTH(
    "Model",
    CAR_VALIDATION_LIMITS.MODEL.MAX
  ),
  YEAR_MIN: `Year must be at least ${CAR_VALIDATION_LIMITS.YEAR.MIN}`,
  YEAR_MAX: `Year cannot exceed ${CAR_VALIDATION_LIMITS.YEAR.MAX}`,
  
  PRICE_MIN: VALIDATION_MESSAGES.POSITIVE_NUMBER("Price per day"),
  SEATS_MIN: `Seats must be at least ${CAR_VALIDATION_LIMITS.SEATS.MIN}`,
  SEATS_MAX: `Seats cannot exceed ${CAR_VALIDATION_LIMITS.SEATS.MAX}`,
} as const;
