import { ROOM_VALIDATION_LIMITS } from "../../limit/room/room.limit";
import VALIDATION_MESSAGES from "../message.message";

export const ROOM_VALIDATION_MESSAGES = {
  ID_REQUIRED: VALIDATION_MESSAGES.REQUIRED("ID"),
  HOTEL_ID_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Hotel reference"),
  NAME_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Room name"),
  OCCUPANCY_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Occupancy"),
  PRICE_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Price per night"),
  DATE_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Calendar date"),

  NAME_MAX: VALIDATION_MESSAGES.MAX_LENGTH(
    "Room name",
    ROOM_VALIDATION_LIMITS.NAME.MAX
  ),
  NAME_MIN: VALIDATION_MESSAGES.MIN_LENGTH(
    "Room name",
    ROOM_VALIDATION_LIMITS.NAME.MIN
  ),
  OCCUPANCY_MIN: `Occupancy must be at least ${ROOM_VALIDATION_LIMITS.OCCUPANCY.MIN} person`,
  PRICE_MIN: `Price cannot be less than ${ROOM_VALIDATION_LIMITS.PRICE.MIN}`,

  INVALID_ID: VALIDATION_MESSAGES.INVALID_ID,
  INVALID_DATE: VALIDATION_MESSAGES.INVALID_FORMAT("date"),
  CALENDAR_ARRAY: "Availability calendar must be a valid list of dates",
  STATUS_ENUM: "Status must be: available, booked, or maintenance",
} as const;
