import VALIDATION_MESSAGES from "../message.message";
import TOUR_SCHEDULE_LIMITS from "../../limit/tour/tourSchedule.limit";

const TOUR_SCHEDULE_VALIDATION_MESSAGES = {
  TOUR_ID_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Tour ID"),
  PRICE_TIER_ID_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Price Tier ID"),
  START_DATE_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Start Date"),
  END_DATE_REQUIRED: VALIDATION_MESSAGES.REQUIRED("End Date"),
  CAPACITY_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Capacity"),
  AVAILABLE_SLOTS_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Available Slots"),

  INVALID_START_DATE: VALIDATION_MESSAGES.INVALID_FORMAT("Start Date"),
  INVALID_END_DATE: VALIDATION_MESSAGES.INVALID_FORMAT("End Date"),

  MIN_CAPACITY: `Capacity must be at least ${TOUR_SCHEDULE_LIMITS.CAPACITY.MIN} person(s)`,
  MIN_SLOTS: "Available slots cannot be negative",
  DATE_ORDER_ERROR: "End date must be after or equal to start date",
} as const;

export default TOUR_SCHEDULE_VALIDATION_MESSAGES;
