import VALIDATION_MESSAGES from "../message.message";
import TOUR_VALIDATION_LIMITS from "../../limit/tour/tour.limit";

export const TOUR_VALIDATION_MESSAGES = {
  TITLE_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Title"),
  TITLE_MIN: VALIDATION_MESSAGES.MIN_LENGTH(
    "Title",
    TOUR_VALIDATION_LIMITS.TITLE.MIN
  ),
  TITLE_MAX: VALIDATION_MESSAGES.MAX_LENGTH(
    "Title",
    TOUR_VALIDATION_LIMITS.TITLE.MAX
  ),

  DESC_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Description"),
  DESC_MIN: VALIDATION_MESSAGES.MIN_LENGTH(
    "Description",
    TOUR_VALIDATION_LIMITS.DESCRIPTION.MIN
  ),
  DESC_MAX: VALIDATION_MESSAGES.MAX_LENGTH(
    "Description",
    TOUR_VALIDATION_LIMITS.DESCRIPTION.MAX
  ),

  DURATION_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Duration"),
  DURATION_POSITIVE: VALIDATION_MESSAGES.POSITIVE_NUMBER("Duration"),
  DURATION_MIN: `Duration must be at least ${
    TOUR_VALIDATION_LIMITS.DURATION.MIN_MS / 3600000
  } hour(s)`,

  LOCATION_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Location"),
  MAIN_IMAGE_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Main Image"),
  INVALID_IMAGE_URL: VALIDATION_MESSAGES.INVALID_FORMAT("Main Image URL"),

  SLUG_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Slug"),
  SLUG_INVALID: VALIDATION_MESSAGES.SLUG_ERROR,

  CREATED_BY_ID_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Required ID"),
  ID_REQUIRED: VALIDATION_MESSAGES.REQUIRED("ID"),
  ID_INVALID: VALIDATION_MESSAGES.INVALID_ID,
} as const;

export default TOUR_VALIDATION_MESSAGES;
