import { HOTEL_VALIDATION_LIMITS } from "../../limit/hotel/hotel.limit";

import VALIDATION_MESSAGES from "../message.message";

export const HOTEL_VALIDATION_MESSAGES = {
  NAME_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Hotel name"),
  LOCATION_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Hotel location"),
  ADDRESS_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Physical address"),
  IMAGE_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Main image URL"),

  NAME_MIN: VALIDATION_MESSAGES.MIN_LENGTH(
    "Hotel name",
    HOTEL_VALIDATION_LIMITS.NAME.MIN
  ),
  NAME_MAX: VALIDATION_MESSAGES.MAX_LENGTH(
    "Hotel name",
    HOTEL_VALIDATION_LIMITS.NAME.MAX
  ),
  ADDRESS_MIN: VALIDATION_MESSAGES.MIN_LENGTH(
    "Address",
    HOTEL_VALIDATION_LIMITS.ADDRESS.MIN
  ),
  ADDRESS_MAX: VALIDATION_MESSAGES.MAX_LENGTH(
    "Address",
    HOTEL_VALIDATION_LIMITS.ADDRESS.MAX
  ),

  INVALID_IMAGE_URL: VALIDATION_MESSAGES.INVALID_FORMAT("image URL"),
  INVALID_RATING: `Rating must be between ${HOTEL_VALIDATION_LIMITS.RATING.MIN} and ${HOTEL_VALIDATION_LIMITS.RATING.MAX}`,
  AMENITIES_OBJECT: VALIDATION_MESSAGES.INVALID_FORMAT("amenities object"),
  ID_REQUIRED: VALIDATION_MESSAGES.REQUIRED("Hotel ID"),
  INVALID_ID: VALIDATION_MESSAGES.INVALID_FORMAT("Hotel ID"),

  INVALID_COORDINATES:"Invalid longitude or latitude values"

} as const;
